export const products = [
  { id: 1, name: "capuccino", image: "", price: 1000, category: "Coffee" },
  { id: 2, name: "latte", image: "", price: 1000, category: "Coffee" },
  { id: 3, name: "espresso", image: "", price: 1000, category: "Coffee" },
  { id: 4, name: "mocha", image: "", price: 1000, category: "Coffee" },
  { id: 5, name: "macchiato", image: "", price: 1000, category: "Coffee" },
  { id: 6, name: "americano", image: "", price: 1000, category: "Coffee" },
  {
    id: 7,
    name: "caramel macchiato",
    image: "",
    price: 1000,
    category: "Caramel Beverages",
  },
  {
    id: 8,
    name: "caramel latte",
    image: "",
    price: 1000,
    category: "Caramel Beverages",
  },
  {
    id: 9,
    name: "caramel cappuccino",
    image: "",
    price: 1000,
    category: "Caramel Beverages",
  },
  {
    id: 10,
    name: "caramel espresso",
    image: "",
    price: 1000,
    category: "Caramel Beverages",
  },
  {
    id: 11,
    name: "caramel mocha",
    image: "",
    price: 1000,
    category: "Caramel Beverages",
  },
  {
    id: 12,
    name: "caramel macchiato",
    image: "",
    price: 1000,
    category: "Caramel Beverages",
  },
  {
    id: 13,
    name: "caramel americano",
    image: "",
    price: 1000,
    category: "Caramel Beverages",
  },
  {
    id: 14,
    name: "caffe mocha",
    image: "",
    price: 1000,
    category: "Caffè Specialties",
  },
  {
    id: 15,
    name: "caffe latte",
    image: "",
    price: 1000,
    category: "Caffè Specialties",
  },
  {
    id: 16,
    name: "caffe cappuccino",
    image: "",
    price: 1000,
    category: "Caffè Specialties",
  },
  {
    id: 17,
    name: "caffe espresso",
    image: "",
    price: 1000,
    category: "Caffè Specialties",
  },
  {
    id: 18,
    name: "caffe mocha",
    image: "",
    price: 1000,
    category: "Caffè Specialties",
  },
  {
    id: 19,
    name: "caffe macchiato",
    image: "",
    price: 1000,
    category: "Caffè Specialties",
  },
  {
    id: 20,
    name: "caffe americano",
    image: "",
    price: 1000,
    category: "Caffè Specialties",
  },
];
